### ISSUE TITLE
RPG_Maps.h missing

### ISSUE THREAD

**Issue by DavidCostaWR** [Joseph21-6147/From-ConsoleGameEngine-to-PixelGameEngine#1]
@Joseph21-6147, I'm looking through the RPG PGE version, but there seems to be missing the maps files (RPG_Maps.h and RPG_Maps.cpp).
The header file is included in the RPG_Engine.h.
I would appreciate if you could make the files available.

Thanks for your time.

**Comment by Joseph21-6147** [comment]
Thanks for the heads up. Added the missing files.
